# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Adds read more feature
excerpt_separator: "<!-- more -->"

# Setup
title:            Thoughts
tagline:          'UX Design'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://blog.jeya.io
baseurl:          /

author:
  name:           'Jeya Karthika'
  url:            https://twitter.com/ItsJkTweeting

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jeyakarthika/blog

